version: "3"

networks:
  center:
    external: true

services:
    app:
      image: tindy2013/subconverter:0.7.1
      container_name: subconverter
      restart: unless-stopped
      networks:
        - center
      ports:
        - "25500:25500"