services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: 192.168.12.173
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://192.168.12.173:8929"
        gitlab_rails["gitlab_shell_ssh_port"] = 2224
    ports:
      - 8929:8929
      - 2224:22
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: 256m
    networks:
      - center

networks:
  center:
    name: center
