version: "3"

networks:
  center:
    external: true

services:
  server:
    image: jenkinsci/blueocean
    container_name: jenkins
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    privileged: true
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - center
    ports:
      - "5001:8080"