version: "3"

networks:
  center:
    external: true

services:
  server:
    image: vault:1.9.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    restart: always
    volumes:
      - ./config.json:/vault/config/config.json
      - ./file:/vault/file
      - ./logs:/vault/logs
    entrypoint: vault server -config /vault/config/config.json
    networks:
      - center
    ports:
      - "8200:8200"