services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - bridge
    ports:
      - "9000:9000"
      # - "9443:9443"

volumes:
  portainer-data:
    name: "portainer-data"

networks:
  bridge:
