version: "3"

networks:
  center:
    external: true

services:
  server:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
        - center
    ports:
      - "9000:9000"
      # - "9443:9443"