services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - syncthing-data:/var/syncthing
    networks:
      - center
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp

volumes:
  syncthing-data:
    name: "syncthing-data"

networks:
  center:
    name: center
