version: "3"

volumes:
  data:
networks:
  bridge:

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - data:/var/syncthing
    networks:
      - bridge
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
