version: "3"

networks:
  center:
    external: true

services:
  app:
    image: telegraf:1.19.0
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - center
