version: "3"

networks:
  center:
    external: true

services:
  app:
    image: influxdb:2.0.7
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=xxx
      - DOCKER_INFLUXDB_INIT_ORG=xxx
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xxx
    # docker安全验证
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    networks:
      - center
    ports:
      - "8086:8086"
